# This workflow will run cypress image snapshot tests

name: Cypress Image Snapshots
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install, build storybook, and run cypress tests
        run: |
          yarn install
          yarn storybook:build
          yarn cypress
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: snapshots
          path: cypress/snapshots/
